version: '3.8'
services:

  php-fpm:
    build: /php-fpm
    container_name: php-fpm
    working_dir: /application
    volumes:
    - ./:/application
    - /php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    networks:
      - net_prueba
    depends_on:
      - reverseproxy
  db:
    image: mariadb:10.5.8
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_USER: admin
    # volumes:
    #   - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - net_prueba
        phpmyadmin:
    build: phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - net-prueba
    depends_on:
      - db
      - reverseproxy
    environment:
      - VIRTUAL_HOST=phpmyadmin.com
    networks:
      -  net_prueba
  laravel:
    image: nginx:alpine
    container_name: nginxLaravel
    working_dir: /application
    volumes:
      - .:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      -  net_prueba
    depends_on:
      - angular
      - db
